name: Secure Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# GitHub Actions ko permissions dena taake page publish ho sake
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Compiler aur Obfuscator dependencies install karna
      - name: Initialize NPM and Install Obfuscator
        run: |
          npm init -y
          npm install javascript-obfuscator

      # compile.js script run karke files generate karna
      - name: Run Compiler Script
        run: node compile.js

      - name: Setup Pages Configuration
        uses: actions/configure-pages@v4

      # Sirf 'dist' folder ko server par bhejna (taki raw compile.js aur data.json chhup sakein)
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
